### ISSUE TITLE
Finished MVP - User Auth

### ISSUE THREAD

**Issue by masonanders** [masonanders/SoundWaves#3]
- [x] User & session backend auth
   - [x] Property validations
   - [x] `api` routes & `json` rendering
- [x] User & session frontend auth
   - [x] Bootstrapped user
   - [x] Frontend protected routes & redirects
- [x] Splash Page styled
   - [x] Renders errors
   - [x] Persists username upon modal close
   - [x] Cross-browser compatibility 
   - [x] Demo login

**Comment by masonanders** [comment]
[Live view](https://soundwaves-soundcloud-clone.herokuapp.com/#/)

**Comment by s-pangburn** [comment]
I am just about to take a look at this, but please add that live link to your wiki as well!

- [x] Live link on wiki

**Comment by masonanders** [comment]
Got it on there

**Comment by s-pangburn** [comment]
- [x] "Try a demo login" is kind of an awkward way to word it imo. It sounds more like... we're _attempting_ a demo login instead of logging in for a demo haha. I'd either go with "Demo Login" or "Try a Demo Account"
  - Hey, nice demo animation! Super slick 😄 
- [x] I would round the corners of your login modal slightly.
- [x] Pressing enter in the login form after entering my username should advance the form. Right now I have to actually click the button.
- [x] Pressing enter on entering a password doesn't submit the form either. But Chrome asks me if I want to remember the password? You should definitely submit the form on enter.
- [x] If we're doing the two-step form like this, it would actually feel a lot more natural if it directed you to login or signup based on whether that username exists or not. Otherwise, it's kind of awkward to get "Invalid username/password combination" and have to click back because you didn't enter the right username/meant to sign up instead of sign in, etc.
  - [x] Also, it's kind of awkward to click sign up, then get "username has already been taken" and have to click back to get back to the username input.
  - [ ] This could alternatively be solved by jumping back to the first (username) input upon failure, but dynamic selection would feel much nicer imo.
- [ ] If you don't have your form dynamically select login or signup based on the existence of the username, there should be a link in the form to switch between login and signup. ("Have an account? Sign in.") That sort of thing.
- [x] Clicking anywhere outside of your modal should close it.
- [x] Set `font-weight: 500` for your "Welcome!" h1 element. It's a nice in-between not-bold and full-bold (like half-bold?) and reinforced the hierarchy of the form.
- [x] Your buttons should probably lighten or darken on hover. This is more just personal taste on my part, but I think it makes the site feel more dynamic and interactive.

Otherwise, it's looking good Mason! Awesome job, and great polish! Address this feedback and you should be good to go full-steam ahead on your next feature. 👍

**Comment by s-pangburn** [comment]
- [x] Oh, also, going to a random route `https://soundwaves-soundcloud-clone.herokuapp.com/#/sdlkfjdslfjslkdjfslkfj` should redirect to root. You should be able to accomplish this with a `<Switch>` in your `App.jsx`.

**Comment by masonanders** [comment]
I survived the battle against the seemingly infinite hoard of bungs and my page seems to be working optimally now. I set it up so that sign will redirect you to new user if you type in a username that does not exist and the other way around it just alerts you that the username has been taken. Let me know what you think!

**Comment by s-pangburn** [comment]
- [x] Your user dropdown doesn't display any text right now? I think this is a bug. I guessed that the second `<li>` was probably Logout and was right, but try to fix this.
- [x] For some reason, your form bugs out when I press enter and the username disappears? Even if the input fails and there are errors, the username disappears.
- [x] Your signup form doesn't switch to login the way the login does? This isn't actually a big deal if this would be a huge pain for you to do in both forms, since sign up is more explicitly about making an account, but I just expected both would work the same.

That's really it though! Address these things and I'll mark this MVP complete! 🙂

**Comment by masonanders** [comment]
I'm not seeing the same bug with the dropdown, not sure why that would be doing that but that dropdown seems to hate me and cause as much trouble as it possibly can so that makes sense. I'll repush to heroku and investigate, let me know if you're still getting the bug.

Again, I can't replicate the bug with the disappearing username... Not sure what's up. I'll check out my site on another computer.

It wouldn't be a huge pain to switch the create account action but my idea was that if someone was trying to make an account it would be a pain if several of the first usernames they tried were taken and they had to navigate out of the sign-in form each time whereas with existing users if they mistype they get navigated to the sign up form and go back once and type in their username more carefully.

**Comment by masonanders** [comment]
I think I just hit the username bug, you were talking about the username in the header not the input right? I'll get on that

**Comment by s-pangburn** [comment]
Ah, excellent point about the taken usernames. Yeah, just leave it as-is 🙂 I can show you what I mean by the dropdown once lunch is over.

**Comment by masonanders** [comment]
Stephen this dropdown is becoming the utter bane of my existence

**Comment by s-pangburn** [comment]
Haha, sorry to hear, maybe I can help you out when I swing by? 😄

**Comment by s-pangburn** [comment]
👍
